# Generated by Django 4.2.1 on 2023-05-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='custom_id',
            field=models.BigIntegerField(default=1685509714, primary_key=True, serialize=False),
        ),
    ]
