# Generated by Django 4.2.1 on 2023-05-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_todo_id_todo_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.BigIntegerField(default=1685509852, primary_key=True, serialize=False),
        ),
    ]
